version = 1

exclude_patterns = [
  "**/node_modules/",
  "dist/**"
]

test_patterns = [
  "**/__tests__/**",
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "mocha"
  ]