// This file is automatically generated. Do not edit.
 import TextChannel from './structures/compiled/TextChannel.js.json' assert { type: 'json' };
 import Thread from './structures/compiled/Thread.js.json' assert { type: 'json' };
 import Reaction from './structures/compiled/Reaction.js.json' assert { type: 'json' };
 import AuditLog from './structures/compiled/AuditLog.js.json' assert { type: 'json' };
 import Channel from './structures/compiled/Channel.js.json' assert { type: 'json' };
 import ModalResponse from './structures/compiled/ModalResponse.js.json' assert { type: 'json' };
 import Member from './structures/compiled/Member.js.json' assert { type: 'json' };
 import Guild from './structures/compiled/Guild.js.json' assert { type: 'json' };
 import User from './structures/compiled/User.js.json' assert { type: 'json' };
 import ScheduledEvent from './structures/compiled/ScheduledEvent.js.json' assert { type: 'json' };
 import Interaction from './structures/compiled/Interaction.js.json' assert { type: 'json' };
 import Attachment from './structures/compiled/Attachment.js.json' assert { type: 'json' };
 import SlashCommand from './structures/compiled/SlashCommand.js.json' assert { type: 'json' };
 import Message from './structures/compiled/Message.js.json' assert { type: 'json' };
 import VoiceChannel from './structures/compiled/VoiceChannel.js.json' assert { type: 'json' };
 import Invite from './structures/compiled/Invite.js.json' assert { type: 'json' };
 import VoiceState from './structures/compiled/VoiceState.js.json' assert { type: 'json' };
 import Sticker from './structures/compiled/Sticker.js.json' assert { type: 'json' };
 import OptionSelect from './structures/compiled/OptionSelect.js.json' assert { type: 'json' };
 import Role from './structures/compiled/Role.js.json' assert { type: 'json' };
 import Emoji from './structures/compiled/Emoji.js.json' assert { type: 'json' };
 import ButtonClick from './structures/compiled/ButtonClick.js.json' assert { type: 'json' };
 export default {
 TextChannel,
 Thread,
 Reaction,
 AuditLog,
 Channel,
 ModalResponse,
 Member,
 Guild,
 User,
 ScheduledEvent,
 Interaction,
 Attachment,
 SlashCommand,
 Message,
 VoiceChannel,
 Invite,
 VoiceState,
 Sticker,
 OptionSelect,
 Role,
 Emoji,
 ButtonClick,
 };
