module.exports = {
  Message: require("./src/structures/compiled/Message.js.json"),
  ScheduledEvent: require("./src/structures/compiled/ScheduledEvent.js.json"),
  TextChannel: require("./src/structures/compiled/TextChannel.js.json"),
  Member: require("./src/structures/compiled/Member.js.json"),
  ModalResponse: require("./src/structures/compiled/ModalResponse.js.json"),
  Role: require("./src/structures/compiled/Role.js.json"),
  Emoji: require("./src/structures/compiled/Emoji.js.json"),
  Attachment: require("./src/structures/compiled/Attachment.js.json"),
  User: require("./src/structures/compiled/User.js.json"),
  Thread: require("./src/structures/compiled/Thread.js.json"),
  Channel: require("./src/structures/compiled/Channel.js.json"),
  ButtonClick: require("./src/structures/compiled/ButtonClick.js.json"),
  Reaction: require("./src/structures/compiled/Reaction.js.json"),
  Interaction: require("./src/structures/compiled/Interaction.js.json"),
  AuditLog: require("./src/structures/compiled/AuditLog.js.json"),
  Invite: require("./src/structures/compiled/Invite.js.json"),
  VoiceState: require("./src/structures/compiled/VoiceState.js.json"),
  SlashCommand: require("./src/structures/compiled/SlashCommand.js.json"),
  Guild: require("./src/structures/compiled/Guild.js.json"),
  Sticker: require("./src/structures/compiled/Sticker.js.json"),
  OptionSelect: require("./src/structures/compiled/OptionSelect.js.json"),
  VoiceChannel: require("./src/structures/compiled/VoiceChannel.js.json"),
};
