name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: CXXFLAGS=-std=c++17 npm ci
      - run: CXXFLAGS=-std=c++17 npm run build --if-present

      - name: Build
        uses: erikyo/tsdoc-action@v1
        with:
          source_dir: ./src/*
          output_dir: ./docs
          front_page: README.md
          config_file: tsdoc.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
          cname: gluon.quark.bot
