name: Compile structures

on:
  push:
    branches:
      - main

jobs:
  compile-structures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install JSDoc
        run: npm install -g jsdoc

      - name: Compile structures
        run: |
          for file in $(find ./src/structures -name '*.js');
          do
            echo "Compiling $file"
            jsdoc -X $file > $file.json
          done

      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
            gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
            passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
            git_config_global: true
            git_user_signingkey: true
            git_commit_gpgsign: true

      - name: Add compiled files to commit
        run: git add ./src/structures/*.json

      - name: Commit changes to compiled file
        run: git commit -m "Compiled Files" .
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
            GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
            GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
            GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}

      - name: Push changes to GitHub
        run: git push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}