name: Node.js CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npx prettier . --check
      - run: CXXFLAGS=-std=c++17 npm ci
      - run: CXXFLAGS=-std=c++17 npm run build --if-present
      - run: npm test
